<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Appointment;
use App\Models\Service;
use App\Models\User;
use App\Models\Employee;
use Carbon\Carbon;

class AppointmentSeeder extends Seeder
{
    public function run()
    {
        // Get all services
        $services = Service::all();

        // Get all employees
        $employees = Employee::all();

        // Get all clients (users with subscriber role)
        $clients = User::role('subscriber')->get();

        if ($clients->isEmpty() || $services->isEmpty() || $employees->isEmpty()) {
            $this->command->error('Please run UserSeeder and ServiceSeeder first!');
            return;
        }

        // Status options
        $statuses = [
            'Pending payment',
            'Processing',
            'Confirmed',
            'Cancelled',
            'Completed',
            'On Hold',
            'Rescheduled',
            'No Show'
        ];

        // Generate appointments for the last 7 days
        for ($i = 0; $i < 30; $i++) {
            $date = Carbon::now()->subDays(rand(0, 7));
            $time = Carbon::createFromTime(rand(9, 17), rand(0, 3) * 15, 0);

            $service = $services->random();
            $employee = $employees->random();
            $client = $clients->random();

            Appointment::create([
                'name' => 'Test Appointment ' . ($i + 1),
                'email' => $client->email,
                'phone' => '06' . rand(10000000, 99999999),
                'service_id' => $service->id,
                'employee_id' => $employee->id,
                'user_id' => $client->id,
                'booking_id' => 'BK' . str_pad($i + 1, 6, '0', STR_PAD_LEFT),
                'booking_date' => $date->format('Y-m-d'),
                'booking_time' => $time->format('H:i'),
                'status' => $statuses[array_rand($statuses)],
                'amount' => rand(50, 200),
                'notes' => 'This is a test appointment generated by the seeder.',
                'created_at' => $date,
                'updated_at' => $date,
            ]);
        }

        $this->command->info('Appointments seeded successfully!');
    }
}
